spring:
  main:
    web-application-type: none
  application:
    name: loan-evaluation-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/sinkdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: secret

loan:
  input:
    topic: loan-requests
  output:
    topic: loan-evaluation-results