services:
  kafka:
    image: landoop/fast-data-dev:latest
    container_name: kafka
    environment:
      - ADV_HOST=127.0.0.1
      - SAMPLEDATA=0
      - RUNTESTS=0
    ports:
      - 3030:3030
      - 9092:9092
      - 2181:2181
      - 8081:8081
      - 8083:8083
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10s
      timeout: 10s
      retries: 5