/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tolopolgyservice.Tolopolgyservice.topology;

@org.apache.avro.specific.AvroGenerated
public interface AppProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AppProtocol\",\"namespace\":\"com.tolopolgyservice.Tolopolgyservice.topology\",\"types\":[{\"type\":\"enum\",\"name\":\"EvaluationResult\",\"symbols\":[\"APPROVED\",\"REJECTED\",\"REVIEW_NEEDED\"]},{\"type\":\"record\",\"name\":\"LoanResponse\",\"fields\":[{\"name\":\"requestId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"account\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"amount\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":14,\"scale\":2}},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"result\",\"type\":\"EvaluationResult\"}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends AppProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.tolopolgyservice.Tolopolgyservice.topology.AppProtocol.PROTOCOL;
  }
}